### ISSUE TITLE
睡眠问题

### ISSUE THREAD

**Issue by alg037** [gclm/Hackintosh-Lenovo-V310-I5-6200U#1]
你好，我的电脑室thinkpad v310-14isk,用了你的EFI后可以正常安装，但是合上笔记本盖子后，自己笨自动睡眠，之后就再也无法唤醒了，只能重启操作，请问你的笔记本碰到过这个问题吗？希望你能帮到我

**Comment by gclm** [comment]
这个问题很好解决，设置里面有个电源设置，你设置硬盘不休眠就可以了
