### ISSUE TITLE
Elan PS2 touchpad

### ISSUE THREAD

**Issue by brunocannavina** [gclm/Hackintosh-Lenovo-V310-I5-6200U#2]
Does your Elan touchpad work fine? 
i can't get it to work. Only mouse

**Comment by Wilber666** [comment]
> Does your Elan touchpad work fine?
> i can't get it to work. Only mouse

Do your WiFi work well?
（I have seen your comment on another issue）

**Comment by gclm** [comment]
不好意思，我的WiFi和触摸板和蓝牙无法正常使用，采用的是usb网卡和usb键鼠

**Comment by brunocannavina** [comment]
No Wilber666, the wifi does not work at all.

**Comment by Wilber666** [comment]
My laptop uses QCA9377,the bluetooth is working,but wifi can't be drived.So I use a USB network card for hackintosh and it is working well.![image](https://user-images.githubusercontent.com/62875848/93951830-fdd9c900-fd79-11ea-833f-078072aeef9e.jpeg)![image](https://user-images.githubusercontent.com/62875848/93951838-0205e680-fd7a-11ea-9668-85c835b5389f.jpeg)![image](https://user-images.githubusercontent.com/62875848/93951845-07633100-fd7a-11ea-9f84-12c5bd302498.jpeg)

**Comment by Wilber666** [comment]
[归档.zip](https://github.com/gclm/Hackintosh-Lenovo-V310-I5-6200U/files/5264892/default.zip)
Hi brunocannavina,you can use this to update your kexts.(Also including my touchpad kext) @brunocannavina
